apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodetest-01
  labels:
    name: nodetest-01
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: nodetest-01
    spec:
      containers:
      - name: nodetest-01
        image: onlydevelop/node-test:0.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodetest-01
  labels:
    name: nodetest-01
spec:
  ports:
    # the port that this service should serve on
  - port: 3000
    targetPort: 3000
  selector:
	name: nodetest-01
